"""add settlement_status to finance_records

Revision ID: 27631e007880
Revises: c934fe6814f0
Create Date: 2026-04-05 19:09:12.998469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27631e007880'
down_revision: Union[str, Sequence[str], None] = 'c934fe6814f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settlement_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_records', schema=None) as batch_op:
        batch_op.drop_column('settlement_status')

    # ### end Alembic commands ###
