"""add quotations and customer_assets tables

Revision ID: 43b5f12ec9ec
Revises: 475cd73e5207
Create Date: 2026-04-05 21:25:44.862319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b5f12ec9ec'
down_revision: Union[str, Sequence[str], None] = '475cd73e5207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_assets',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('annual_fee', sa.Float(), nullable=True),
    sa.Column('account_info', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_assets_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_assets_expiry_date'), ['expiry_date'], unique=False)

    op.create_table('quotations',
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('validity_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('discount_note', sa.String(length=500), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotations_quotation_number'), ['quotation_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_quotations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_validity_date'), ['validity_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_validity_date'))
        batch_op.drop_index(batch_op.f('ix_quotations_status'))
        batch_op.drop_index(batch_op.f('ix_quotations_quotation_number'))

    op.drop_table('quotations')
    with op.batch_alter_table('customer_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_assets_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_customer_assets_customer_id'))

    op.drop_table('customer_assets')
    # ### end Alembic commands ###
