"""initial schema from existing models

Revision ID: 7dab35076a9c
Revises:
Create Date: 2026-04-05 19:01:05.622288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7dab35076a9c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix unnamed FK constraint on finance_records
    with op.batch_alter_table("finance_records", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_finance_records_related_record", "finance_records", ["related_record_id"], ["id"]
        )

    # Fix login_attempts column type (was incorrectly detected as BOOLEAN)
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("login_attempts", existing_type=sa.BOOLEAN(), type_=sa.Integer(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("login_attempts", existing_type=sa.Integer(), type_=sa.BOOLEAN(), existing_nullable=False)

    with op.batch_alter_table("finance_records", schema=None) as batch_op:
        batch_op.drop_constraint("fk_finance_records_related_record", type_="foreignkey")

    # ### end Alembic commands ###
