"""verify_missing_columns_v2

Revision ID: c8de50e8001e
Revises: 32d5834cf68a
Create Date: 2026-04-11 13:56:58.448055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8de50e8001e'
down_revision: Union[str, Sequence[str], None] = '32d5834cf68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_exists(connection, index_name: str) -> bool:
    """Check if an index exists in the database."""
    result = connection.execute(
        sa.text("SELECT name FROM sqlite_master WHERE type='index' AND name=:name"),
        {"name": index_name}
    )
    return result.fetchone() is not None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # work_hour_logs: drop indexes only if they exist, then drop table
    conn = op.get_bind()
    with op.batch_alter_table('work_hour_logs', schema=None) as batch_op:
        if _index_exists(conn, 'idx_work_hour_logs_log_date'):
            batch_op.drop_index(batch_op.f('idx_work_hour_logs_log_date'))
        if _index_exists(conn, 'idx_work_hour_logs_project_id'):
            batch_op.drop_index(batch_op.f('idx_work_hour_logs_project_id'))

    op.drop_table('work_hour_logs')
    with op.batch_alter_table('acceptances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_acceptances_acceptance_date'))
        batch_op.drop_index(batch_op.f('idx_acceptances_delivery_package_id'))
        batch_op.drop_index(batch_op.f('idx_acceptances_project_id'))
        batch_op.drop_index(batch_op.f('idx_acceptances_reminder_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'delivery_packages', ['delivery_package_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'milestones', ['milestone_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'reminders', ['reminder_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('account_handovers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'deliverables', ['deliverable_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('annotation_tasks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('completed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_annotation_tasks_dataset_version_id'))
        batch_op.drop_index(batch_op.f('idx_annotation_tasks_project_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'dataset_versions', ['dataset_version_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('change_orders', schema=None) as batch_op:
        batch_op.alter_column('confirmed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_change_orders_contract_id'))
        batch_op.drop_index(batch_op.f('idx_change_orders_status'))
        batch_op.create_unique_constraint(None, ['order_no'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('extra_days')
        batch_op.drop_column('client_confirmed_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('extra_amount')
        batch_op.drop_column('client_rejected_at')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_contracts_expected_payment_date'))
        batch_op.drop_index(batch_op.f('idx_contracts_quotation_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'quotations', ['quotation_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_customers_risk_level'))

    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_dataset_versions_dataset_id'))
        batch_op.drop_index(batch_op.f('idx_dataset_versions_status'))
        batch_op.create_unique_constraint('uq_dataset_version', ['dataset_id', 'version_no'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'datasets', ['dataset_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_datasets_project_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_deliverables_acceptance_id'))
        batch_op.drop_index(batch_op.f('idx_deliverables_delivery_date'))
        batch_op.drop_index(batch_op.f('idx_deliverables_delivery_package_id'))
        batch_op.drop_index(batch_op.f('idx_deliverables_project_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'acceptances', ['acceptance_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('delivery_package_id')

    with op.batch_alter_table('delivery_packages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('delivered_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_delivery_packages_project_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('experiment_dataset_versions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_experiment_dataset_versions_experiment_id'))
        batch_op.drop_index(batch_op.f('idx_experiment_dataset_versions_version_id'))
        batch_op.create_unique_constraint('uq_exp_dv', ['experiment_id', 'dataset_version_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'dataset_versions', ['dataset_version_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('export_batches', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_export_batches_accounting_period'))
        batch_op.drop_index(batch_op.f('idx_export_batches_batch_id'))
        batch_op.drop_index(batch_op.f('idx_export_batches_created_at'))
        batch_op.create_unique_constraint(None, ['batch_id'])

    with op.batch_alter_table('finance_records', schema=None) as batch_op:
        batch_op.alter_column('export_batch_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('reconciliation_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_index(batch_op.f('idx_finance_records_accounting_period'))
        batch_op.drop_index(batch_op.f('idx_finance_records_export_batch_id'))
        batch_op.drop_index(batch_op.f('idx_finance_records_invoice_direction'))
        batch_op.drop_index(batch_op.f('idx_finance_records_invoice_id'))
        batch_op.drop_index(batch_op.f('idx_finance_records_invoice_no'))
        batch_op.drop_index(batch_op.f('idx_finance_records_reconciliation_status'))
        batch_op.drop_index(batch_op.f('idx_finance_records_related_project_id'))
        batch_op.create_index(batch_op.f('ix_finance_records_related_project_id'), ['related_project_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'export_batches', ['export_batch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['related_project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fixed_costs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_fixed_costs_category'))
        batch_op.drop_index(batch_op.f('idx_fixed_costs_effective_date'))
        batch_op.drop_index(batch_op.f('idx_fixed_costs_project_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('input_invoices', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_input_invoices_invoice_date'))
        batch_op.drop_index(batch_op.f('idx_input_invoices_project_id'))
        batch_op.drop_index(batch_op.f('idx_input_invoices_vendor_name'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('issued_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('received_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('verified_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_invoices_contract_id'))
        batch_op.drop_index(batch_op.f('idx_invoices_invoice_date'))
        batch_op.drop_index(batch_op.f('idx_invoices_status'))
        batch_op.create_unique_constraint(None, ['invoice_no'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('maintenance_periods', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_maintenance_periods_end_date'))
        batch_op.drop_index(batch_op.f('idx_maintenance_periods_project_id'))
        batch_op.drop_index(batch_op.f('idx_maintenance_periods_renewed_by_id'))
        batch_op.drop_index(batch_op.f('idx_maintenance_periods_status'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'maintenance_periods', ['renewed_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.alter_column('payment_received_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_milestones_payment_status'))

    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_model_versions_experiment_id'))
        batch_op.drop_index(batch_op.f('idx_model_versions_project_id'))
        batch_op.drop_index(batch_op.f('idx_model_versions_status'))
        batch_op.create_unique_constraint('uq_model_ver', ['project_id', 'name', 'version_no'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_experiments', ['experiment_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('package_dataset_versions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_unique_constraint('uq_pkg_dv', ['package_id', 'dataset_version_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'dataset_versions', ['dataset_version_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'delivery_packages', ['package_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('package_model_versions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_unique_constraint('uq_pkg_mv', ['package_id', 'model_version_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'model_versions', ['model_version_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'delivery_packages', ['package_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('close_checklist',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('closed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('profit_cache_updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('quotation_changes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_quotation_changes_quotation_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'quotations', ['quotation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_quotation_items_quotation_id'))
        batch_op.drop_index(batch_op.f('idx_quotation_items_sort_order'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'quotations', ['quotation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('sent_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('accepted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('rejected_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('expired_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_quotations_customer_id'))
        batch_op.drop_index(batch_op.f('idx_quotations_project_id'))
        batch_op.drop_index(batch_op.f('idx_quotations_status'))
        batch_op.drop_index(batch_op.f('idx_quotations_valid_until'))
        batch_op.create_index(batch_op.f('ix_quotations_quote_no'), ['quote_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_quotations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_valid_until'), ['valid_until'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'contracts', ['converted_contract_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_releases_deliverable_id'))
        batch_op.drop_index(batch_op.f('idx_releases_is_current_online'))
        batch_op.drop_index(batch_op.f('idx_releases_project_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'deliverables', ['deliverable_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('requirement_changes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_requirement_changes_change_order_id'))
        batch_op.drop_index(batch_op.f('idx_requirement_changes_requirement_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'change_orders', ['change_order_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'requirements', ['requirement_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_type', sa.String(length=30), nullable=True, comment='需求类型，如 annotation_spec'))
        batch_op.alter_column('confirmed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_requirements_annotation_task_id'))
        batch_op.drop_index(batch_op.f('idx_requirements_is_current'))
        batch_op.drop_index(batch_op.f('idx_requirements_project_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'annotation_tasks', ['annotation_task_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('training_experiments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('started_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('finished_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_training_experiments_project_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_experiments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_training_experiments_project_id'), ['project_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('finished_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'annotation_tasks', ['annotation_task_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_requirements_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_requirements_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('idx_requirements_annotation_task_id'), ['annotation_task_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('confirmed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('requirement_type')

    with op.batch_alter_table('requirement_changes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'requirements', ['requirement_id'], ['id'])
        batch_op.create_foreign_key(None, 'change_orders', ['change_order_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_requirement_changes_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_requirement_changes_change_order_id'), ['change_order_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'deliverables', ['deliverable_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_releases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_releases_is_current_online'), ['is_current_online'], unique=False)
        batch_op.create_index(batch_op.f('idx_releases_deliverable_id'), ['deliverable_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'contracts', ['converted_contract_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_quotations_valid_until'))
        batch_op.drop_index(batch_op.f('ix_quotations_status'))
        batch_op.drop_index(batch_op.f('ix_quotations_quote_no'))
        batch_op.create_index(batch_op.f('idx_quotations_valid_until'), ['valid_until'], unique=False)
        batch_op.create_index(batch_op.f('idx_quotations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_quotations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_quotations_customer_id'), ['customer_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('expired_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('rejected_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('accepted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('sent_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'quotations_old', ['quotation_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_quotation_items_sort_order'), ['sort_order'], unique=False)
        batch_op.create_index(batch_op.f('idx_quotation_items_quotation_id'), ['quotation_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('quotation_changes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'quotations_old', ['quotation_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_quotation_changes_quotation_id'), ['quotation_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('profit_cache_updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('closed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('close_checklist',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('package_model_versions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'model_versions', ['model_version_id'], ['id'])
        batch_op.create_foreign_key(None, 'delivery_packages', ['package_id'], ['id'])
        batch_op.drop_constraint('uq_pkg_mv', type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('package_dataset_versions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'dataset_versions', ['dataset_version_id'], ['id'])
        batch_op.create_foreign_key(None, 'delivery_packages', ['package_id'], ['id'])
        batch_op.drop_constraint('uq_pkg_dv', type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_experiments', ['experiment_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.drop_constraint('uq_model_ver', type_='unique')
        batch_op.create_index(batch_op.f('idx_model_versions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_model_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_model_versions_experiment_id'), ['experiment_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_milestones_payment_status'), ['payment_status'], unique=False)
        batch_op.alter_column('payment_received_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('maintenance_periods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'maintenance_periods', ['renewed_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_maintenance_periods_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_maintenance_periods_renewed_by_id'), ['renewed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_maintenance_periods_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_maintenance_periods_end_date'), ['end_date'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_invoices_invoice_date'), ['invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_invoices_contract_id'), ['contract_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('verified_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('received_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('issued_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('input_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_input_invoices_vendor_name'), ['vendor_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_input_invoices_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_input_invoices_invoice_date'), ['invoice_date'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('fixed_costs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_fixed_costs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fixed_costs_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_fixed_costs_category'), ['category'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('finance_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['related_project_id'], ['id'])
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_finance_records_related_project_id'))
        batch_op.create_index(batch_op.f('idx_finance_records_related_project_id'), ['related_project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_finance_records_reconciliation_status'), ['reconciliation_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_finance_records_invoice_no'), ['invoice_no'], unique=False)
        batch_op.create_index(batch_op.f('idx_finance_records_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_finance_records_invoice_direction'), ['invoice_direction'], unique=False)
        batch_op.create_index(batch_op.f('idx_finance_records_export_batch_id'), ['export_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_finance_records_accounting_period'), ['accounting_period'], unique=False)
        batch_op.alter_column('reconciliation_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('export_batch_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('export_batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_export_batches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_export_batches_batch_id'), ['batch_id'], unique=1)
        batch_op.create_index(batch_op.f('idx_export_batches_accounting_period'), ['accounting_period'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('experiment_dataset_versions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'dataset_versions', ['dataset_version_id'], ['id'])
        batch_op.create_foreign_key(None, 'training_experiments', ['experiment_id'], ['id'])
        batch_op.drop_constraint('uq_exp_dv', type_='unique')
        batch_op.create_index(batch_op.f('idx_experiment_dataset_versions_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_experiment_dataset_versions_experiment_id'), ['experiment_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('delivery_packages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_delivery_packages_project_id'), ['project_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('delivered_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_package_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'acceptances', ['acceptance_id'], ['id'])
        batch_op.create_foreign_key(None, 'delivery_packages', ['delivery_package_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_deliverables_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_deliverables_delivery_package_id'), ['delivery_package_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_deliverables_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_deliverables_acceptance_id'), ['acceptance_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_datasets_project_id'), ['project_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'datasets', ['dataset_id'], ['id'])
        batch_op.drop_constraint('uq_dataset_version', type_='unique')
        batch_op.create_index(batch_op.f('idx_dataset_versions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_dataset_versions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_customers_risk_level'), ['risk_level'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'quotations_old', ['quotation_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_contracts_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_contracts_expected_payment_date'), ['expected_payment_date'], unique=False)

    with op.batch_alter_table('change_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_rejected_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('extra_amount', sa.DECIMAL(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('client_confirmed_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('extra_days', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_change_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_change_orders_contract_id'), ['contract_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('confirmed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('annotation_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'dataset_versions', ['dataset_version_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_annotation_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_annotation_tasks_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('account_handovers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'deliverables', ['deliverable_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('acceptances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'milestones', ['milestone_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'delivery_packages', ['delivery_package_id'], ['id'])
        batch_op.create_foreign_key(None, 'reminders', ['reminder_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_acceptances_reminder_id'), ['reminder_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_acceptances_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_acceptances_delivery_package_id'), ['delivery_package_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_acceptances_acceptance_date'), ['acceptance_date'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('work_hour_logs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('log_date', sa.DATE(), nullable=False),
    sa.Column('hours_spent', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('task_description', sa.TEXT(), nullable=False),
    sa.Column('deviation_note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_hour_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_work_hour_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_work_hour_logs_log_date'), ['log_date'], unique=False)

    # ### end Alembic commands ###
